const fs = require('fs');
let code = fs.readFileSync('src/pages/SportPage.tsx', 'utf8');

const targetStr = `                          <div style="margin-top: 60px; text-align: center; font-size: 14px; color: #94a3b8; font-weight: 600;">
                            Generated by Sports Management System
                          </div>`;

const playersHtmlLogic = `
                      const sortedPlayersForReport = [...aggregatedStats].sort((a, b) => ((b as any)[topPerformer.primaryStat] || 0) - ((a as any)[topPerformer.primaryStat] || 0));
                      const allPlayersHtml = \`
                        <h3 style="font-size: 20px; font-weight: 800; text-transform: uppercase; color: #0f172a; margin-top: 60px; margin-bottom: 20px;">All Players Ranking</h3>
                        <table style="width: 100%; border-collapse: collapse; text-align: left; font-family: sans-serif;">
                          <thead>
                            <tr style="background: #f1f5f9; color: #475569; text-transform: uppercase; font-size: 12px;">
                              <th style="padding: 12px; border-bottom: 2px solid #e2e8f0;">Rank</th>
                              <th style="padding: 12px; border-bottom: 2px solid #e2e8f0;">Player</th>
                              <th style="padding: 12px; border-bottom: 2px solid #e2e8f0;">Team</th>
                              \${S_STATS[sport as keyof typeof S_STATS]?.map(st => \`<th style="padding: 12px; border-bottom: 2px solid #e2e8f0;">\${st.replace("_", " ")}</th>\`).join('')}
                            </tr>
                          </thead>
                          <tbody>
                            \${sortedPlayersForReport.map((p, idx) => {
                               const pl = playersMap[p.player_id];
                               const tm = pl ? teamsMap[pl.team_id] : null;
                               return \`
                                 <tr style="border-bottom: 1px solid #e2e8f0;">
                                   <td style="padding: 12px; font-weight: 600; color: \${idx === 0 ? '#fbbf24' : '#64748b'};">\${idx === 0 ? '🏆 MVP' : idx + 1}</td>
                                   <td style="padding: 12px; font-weight: 600; color: #0f172a;">\${pl?.player_name || 'Unknown'}</td>
                                   <td style="padding: 12px; color: #64748b;">\${tm?.team_name || 'Unknown'}</td>
                                   \${S_STATS[sport as keyof typeof S_STATS]?.map(st => \`<td style="padding: 12px; font-weight: 500;">\${(p as any)[st] || 0}</td>\`).join('')}
                                 </tr>
                               \`;
                            }).join('')}
                          </tbody>
                        </table>
                      \`;
`;

// Insert the logic before printHtml call.
const onClickTarget = `onClick={() => {
                      const statsHtml = S_STATS[sport as keyof typeof S_STATS]?.map(st => \``;

code = code.replace(onClickTarget, `onClick={() => {\n${playersHtmlLogic}\n                      const statsHtml = S_STATS[sport as keyof typeof S_STATS]?.map(st => \``);

// Insert the HTML string inside the template literal.
code = code.replace(targetStr, `\${allPlayersHtml}\n${targetStr}`);

fs.writeFileSync('src/pages/SportPage.tsx', code);
